name: Import open source standard labels

on:
  push:
    branches: [ master, staged ]

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: EddieHubCommunity/gh-action-open-source-labels@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: 'Heptagram-Bot'
        repository-name: 'Heptagram'
